version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-compress"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-bolgds3adx0r"
s3_prefix = "image-compress"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UncompressedBucketName=\"uncompressedphotos\" CompressedBucketName=\"compressedphotos\""
image_repositories = []
